### ISSUE TITLE
Migrate unit management to `Unitful.jl`

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/AtomicAndPhysicalConstants.jl#46] opened 2024-09-09 16:56 UTC
We should use [`Unitful.jl`](https://github.com/PainterQubits/Unitful.jl) and use [`UnitfulUS.jl`](https://github.com/PainterQubits/UnitfulUS.jl)

**Comment by DavidSagan** [comment] 2024-09-09 17:26
Duplicate of #47.

**Closed by DavidSagan** 2024-09-09 17:26 UTC
